export const products = [
  {
    id: 1,
    name: "Grey",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages10.jpg",
    imageAlt: "A black bottle of Grey by Dolce & Gabbana",
    price: "44.99",
    sale: false,
    brand: "Dolce & Gabbana",
    category: "men",
    collection: "fall",
  },
  {
    id: 2,
    name: "Intense",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages02.jpg",
    imageAlt: "A bottle of Intense by Hugo Boss",
    price: "83.99",
    sale: false,
    brand: "Hugo Boss",
    category: "men",
    collection: "winter",
  },
  {
    id: 3,
    name: "Vera Wang Men",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages03.jpg",
    imageAlt: "A blank bottle of Vera Wang Men by Vera Wang",
    price: "34.99",
    sale: false,
    brand: "Vera Wang",
    category: "men",
    collection: "spring",
  },
  {
    id: 4,
    name: "Eros",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages16.jpg",
    imageAlt: "A bottle of Eros Flower by Versace",
    price: "91.99",
    sale: false,
    brand: "Versace",
    category: "men",
    collection: "fall",
  },
  {
    id: 5,
    name: "Uomo Born in Roma Yellow Dream",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages04.jpg",
    imageAlt: "A bottle of Uomo Born by Valentino.",
    price: "96.99",
    sale: false,
    brand: "Valentino",
    category: "men",
    collection: "spring",
  },
  {
    id: 6,
    name: "Sauvage",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages05.jpg",
    imageAlt: "A bottle of Coco Noir by Chanel.",
    price: "145.99",
    sale: false,
    brand: "Dior",
    category: "men",
    collection: "winter",
  },
  {
    id: 7,
    name: "Infinite",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages06.jpg",
    imageAlt: "A bottle of Infinite by Hugo Boss.",
    price: "78.99",
    sale: false,
    brand: "Hugo Bos",
    category: "men",
    collection: "spring",
  },
  {
    id: 8,
    name: "Acqua di Gio Pour",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages08.jpg",
    imageAlt: "A bottle of Acqua di Gio Pour by Armani",
    price: "74.99",
    sale: false,
    brand: "Armani",
    category: "men",
    collection: "fall",
  },
  {
    id: 9,
    name: "Burberry for Men",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages09.jpg",
    imageAlt: "A bottle of Burberry for Men by Burberry",
    price: "39.99",
    sale: false,
    brand: "Burberry",
    category: "men",
    collection: "spring",
  },
  {
    id: 10,
    name: "Penhaligons Gift Set",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages01.jpg",
    imageAlt: "Three bottles of different Penhalgions scents",
    price: "375.00",
    sale: true,
    brand: "Penhalgions",
    category: "men",
    collection: "winter",
  },
  {
    id: 11,
    name: "Hugo Boss",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages07.jpg",
    imageAlt: "A bottle of the original Hugo Boss",
    price: "89.99",
    sale: true,
    brand: "Hugo Boss",
    category: "men",
    collection: "summer",
  },
  {
    id: 12,
    name: "The One",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages22.jpg",
    imageAlt: "A black bottle of The One by Dolce & Gabbana",
    price: "77.99",
    sale: true,
    brand: "Dolce & Gabbana",
    category: "men",
    collection: "summer",
  },
  {
    id: 13,
    name: "The Only One",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages12.jpg",
    imageAlt: "A black bottle of The Only One by Dolce & Gabbana",
    price: "95.99",
    brand: "Dolce & Gabbana",
    sale: false,
    category: "womens",
    collection: "winter",
  },
  {
    id: 14,
    name: "Guilty",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages13.jpg",
    imageAlt: "A bottle of Guilty by Gucci",
    price: "64.99",
    brand: "Gucci",
    sale: false,
    category: "womens",
    collection: "spring",
  },
  {
    id: 15,
    name: "Jadore",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages14.jpg",
    imageAlt: "A blank bottle of perfume by Dior",
    price: "134.99",
    brand: "Dior",
    sale: false,
    category: "womens",
    collection: "fall",
  },
  {
    id: 16,
    name: "Illicit Flower",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages15.jpg",
    imageAlt: "A bottle of Illicit Flower by Jimmy Choo",
    price: "57.99",
    brand: "Jimmy Choo",
    sale: false,
    category: "womens",
    collection: "spring",
  },
  {
    id: 17,
    name: "Daisy",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages17.jpg",
    imageAlt: "A bottle of Daisy by Marc Jacobs.",
    price: "151.99",
    brand: "Marc Jacobs",
    sale: false,
    category: "womens",
    collection: "spring",
  },
  {
    id: 18,
    name: "Coco Nior",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages18.jpg",
    imageAlt: "A bottle of Coco Noir by Chanel.",
    price: "145.99",
    brand: "Chanel",
    sale: true,
    category: "womens",
    collection: "winter",
  },
  {
    id: 19,
    name: "Gabrielle",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages19.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: "107.99",
    brand: "Chanel",
    sale: false,
    category: "womens",
    collection: "fall",
  },
  {
    id: 20,
    name: "Decadence",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages20.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: "55.99",
    brand: "Marc Jacobs",
    sale: false,
    category: "womens",
    collection: "spring",
  },
  {
    id: 21,
    name: "My Burberry",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages21.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: "104.99",
    brand: "Burberry",
    sale: false,
    category: "womens",
    collection: "fall",
  },
  {
    id: 22,
    name: "Eternity",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages23.jpg",
    imageAlt: "A bottle of Eternity by Calvin Klein",
    price: "49.99",
    brand: "Calvin Klein",
    sale: true,
    category: "womens",
    collection: "summer",
  },
  {
    id: 23,
    name: "Clover",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages25.jpg",
    imageAlt: "A rollon of Clover by Scentll",
    price: "25.00",
    brand: "Scentll",
    sale: true,
    category: "womens",
    collection: "summer",
  },
  {
    id: 24,
    name: "No. 16",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages26.jpg",
    imageAlt: "A roller of No. 16 by Scentll",
    price: "25.00",
    brand: "Scentll",
    sale: true,
    category: "womens",
    collection: "summer",
  },
  {
    id: 25,
    name: "Sand",
    href: "#",
    imageSrc:
      "https://the-software-guild.s3.amazonaws.com/react/v2107/exerciseRoutingPages27.jpg",
    imageAlt: "a rollon perfume named Sand by Scentll",
    price: "25.00",
    brand: "Scentll",
    sale: true,
    category: "womens",
    collection: "summer",
  },
];
